from .base import AMLProvider

MOCK_RESPONSE = {
    'result': True,
    'balance': 86,
    'amlFlow': 'fast',
    'termsConfirmRequired': False,
    'proMode': '0',
    'discount': 0,
    'discountDueTime': 0,
    'promoFlow': False,
    'data': {
        'riskscore': 0.63,
        'signals': {
            'exchange': 0.317,
            'risky_exchange': 0.017,
            'p2p_exchange': 0,
            'enforcement_action': 0,
            'atm': 0,
            'child_exploitation': 0,
            'dark_market': 0,
            'dark_service': 0,
            'exchange_fraudulent': 0,
            'gambling': 0.594,
            'illegal_service': 0,
            'liquidity_pools': 0.002,
            'marketplace': 0,
            'miner': 0,
            'mixer': 0,
            'other': 0.009,
            'p2p_exchange_mlrisk_high': 0.005,
            'payment': 0.047,
            'ransom': 0,
            'sanctions': 0.002,
            'scam': 0,
            'seized_assets': 0,
            'stolen_coins': 0,
            'terrorism_financing': 0,
            'wallet': 0.005,
            'infrastructure_as_a_service': 0,
            'decentralized_exchange_contract': 0,
            'merchant_services': 0,
            'unnamed_service': 0,
            'malware': 0,
        },
        'updated_at': 1750410539,
        'address': '0xf2e8e0761df9acda6d6b67a219ce41e522647e26',
        'fiat_code_effective': 'usd',
        'counterparty': {
            'address': '0xf2e8e0761df9acda6d6b67a219ce41e522647e26',
            'received_fiat_amount': 8376955,
            'sent_fiat_amount': 8443575,
            'signals': {
                'in': {
                    'exchange': 0.667,
                    'risky_exchange': 0.079,
                    'p2p_exchange': 0,
                    'enforcement_action': 0,
                    'atm': 0,
                    'child_exploitation': 0,
                    'dark_market': 0,
                    'dark_service': 0,
                    'exchange_fraudulent': 0,
                    'gambling': 0.048,
                    'illegal_service': 0,
                    'liquidity_pools': 0.002,
                    'marketplace': 0,
                    'miner': 0,
                    'mixer': 0,
                    'other': 0.017,
                    'p2p_exchange_mlrisk_high': 0.008,
                    'payment': 0.166,
                    'ransom': 0,
                    'sanctions': 0.003,
                    'scam': 0,
                    'seized_assets': 0,
                    'stolen_coins': 0,
                    'terrorism_financing': 0,
                    'wallet': 0.009,
                    'infrastructure_as_a_service': 0,
                    'decentralized_exchange_contract': 0,
                    'merchant_services': 0,
                    'unnamed_service': 0,
                    'malware': 0,
                },
                'out': {
                    'exchange': 0,
                    'risky_exchange': 0,
                    'p2p_exchange': 0,
                    'enforcement_action': 0,
                    'atm': 0,
                    'child_exploitation': 0,
                    'dark_market': 0,
                    'dark_service': 0,
                    'exchange_fraudulent': 0,
                    'gambling': 1,
                    'illegal_service': 0,
                    'liquidity_pools': 0,
                    'marketplace': 0,
                    'miner': 0,
                    'mixer': 0,
                    'other': 0,
                    'p2p_exchange_mlrisk_high': 0,
                    'payment': 0,
                    'ransom': 0,
                    'sanctions': 0,
                    'scam': 0,
                    'seized_assets': 0,
                    'stolen_coins': 0,
                    'terrorism_financing': 0,
                    'wallet': 0,
                    'infrastructure_as_a_service': 0,
                    'decentralized_exchange_contract': 0,
                    'merchant_services': 0,
                    'unnamed_service': 0,
                    'malware': 0,
                },
            },
        },
        'reportedAddressBalance': None,
        'addressDetailsData': {
            'reported_balance_precision': 18,
            'balance_approximate': 0,
        },
        'blackListsConnections': False,
        'hasBlackListFlag': False,
        'pdfReport': '#',
        'memo': '',
        'extras': {
            'tags': ['stake.com', 'deposit'],
            'services': {
                'use_platform': [
                    'Binance',
                    'WhiteBIT',
                    'stake.com',
                    'Bybit',
                    'Cobo',
                    'chainup_custody',
                ],
                'malicious_event': [
                    'Fake_Phishing',
                    'Harmony Horizon Bridge Exploiter',
                ],
                'relation_info': [
                    'OKX Web3 Wallet',
                    'MetaMask',
                    'amilliondollarin.eth',
                ],
            },
        },
        'customerIsB2B': True,
        'uid': '6855252bbd86e138331438',
        'asset': 'BNB',
        'network': 'BSC',
        'status': 'success',
        'timestamp': '2025-06-20 09:08:59',
        'flow': 'advanced',
        '_type': 9,
        'cost': 0,
    },
}


class MockAMLProvider(AMLProvider):
    async def get_aml_data(self, post_data: dict) -> dict:
        return MOCK_RESPONSE
